name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run basic tests
        run: |
          python -m pip install --upgrade pip
          python main.py --help  # Simple test to verify the script runs
